language: cpp
before_script:
    - mkdir build
    - cd build
    - cmake ..
script: make VERBOSE=1
compiler:
    - clang
    - gcc
notifications:
    irc:
        channels:
            - "chat.freenode.net#replicode"
        template:
            - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
